# Default configuration file for strongSwan UML testing.
#
# Copyright (C) 2009 Tobias Brunner
# Hochschule fuer Technik Rapperswil
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.

# All tarballs must have on of the following extensions:
#   .tar, .tar.gz, .tgz, .tar.bz2, .tbz
# Patches must have one of the following extensions:
#   .patch, .patch.gz, .patch.bz2
# All paths to files and directories can be given relative (to the testing
# root) or absolute.
#
# ERB can be used to execute ruby code (<% %> or <%= %> syntax).
#
# The following sections and subsections can be defined.
#
# guests - defines the guests/hosts to be built
# |-defaults - defines the default values for all hosts
# | |-strongswan - the strongswan version to be used. this is either the name
# | |              of a strongswan config as defined in separate section or an
# | |              inline strongswan config (see below for the sections)
# | |-kernel - the kernel to be used. either the name of a kernel config defined
# | |          in a separate section or an inline kernel config
# | |-master - the master file system to be used (folder or tarball)
# | |-templates - default config files etc. that are copied to the guests root
# | |             file system. a directory with the guest's name must exist in
# | |             the directory specified here.
# | |-mem - the memory in MB per guest
# | |-console - a list of consoles to be connected for the guests (xterm|pts).
# |             e.g.
# |               consoles:
# |                 - xterm
# |                 - pts
# |             would connect con1 with an xterm and a pts to con2
# |-hosts - a list of hosts to be built. for each host the defaults set above
#           can be customized.
#           e.g.
#             hosts:
#               - sun
#               - moon:
#                   strongswan: older-version
#               - dave:
#                   mem: 128
#           this would create the three guests sun, moon and dave where for moon
#           a different strongswan version is installed and dave uses 128MB
#           of memory instead of the default value.
#
# kernels - this defines kernel configurations that can be referenced above
# |-NAME - the name of the kernel configuration, used to reference the config
#   |- source - the type of source used to build the kernel. this is on of the
#   |           following values:
#   |             none - an already built kernel can be confgured directly
#   |                    using the 'path' option
#   |             dir - builds the kernel from the sources in the configured
#   |                   directory (directly in that directory)
#   |             git - build the kernel from the sources in the given (local)
#   |                   git repository. using the 'treeish' option, a specific
#   |                   tag, branch or even individual commit can be specified
#   |                   that is then built.
#   |             tar - build the kernel from the given tarball
#   |           this option defaults to none
#   |- path - the path to the kernel or the kernel sources
#   |- treeish - this allows to specify a specific treeish (tag, branch etc.) in
#   |            the git repository that is used to build the kernel. if it is
#   |            set, a tarball is created from that treeish (using git archive)
#   |            and that tarball is then used to build the kernel. if this
#   |            option is omitted or empty, the build takes place directly in
#   |            the unmodified repository (i.e. falls back to 'source: dir').
#   |- patches - this is a list of kernel patches that are applied before
#   |            compiling the sources.
#   |- config - configuration file for the kernel. if it is not defined, the
#               kernel config is assumed to be available in the source dir.
#
# strongswan - this is a list of strongswan configurations that can be
# |            referenced above (very similar to the kernel configurations)
# |- NAME - the name of the strongswan config, used to reference it
#    |- source - this is the same as for the kernel configs above, except there
#    |           is no 'none' option.
#    |- path - same as for the kernel
#    |- treeish - again, same as above
#    |- options - a list of options for the configure script
#                 e.g.
#                   options:
#                     eap_aka: yes # results in --enable-eap-aka
#                     eap_md5: no  # results in --disable-eap-md5
#

guests:
  defaults:
    strongswan: default
    kernel: default
    masterfs: master
    templates: hosts
    mem: 64
    consoles:
      - xterm
  hosts:
    - sun
    - moon
    - dave
    - carol
    - alice
    - venus
    - bob
    - winnetou

kernels:
  default:
    source: git
    path: ~/kernel/linux-2.6/
    treeish: 'v2.6.28'
    patches:
      - ../src/dumm/patches/mconsole-exec-2.6.28.patch
    config: .config-2.6.28

strongswan:
  default:
    source: git
    path: ../
    treeish: master
    options:
      - curl: no
      - ldap: no
      - eap_aka: yes
      - eap_sim: yes
      - eap_sim_file: yes
      - eap_md5: yes
      - eap_mschapv2: yes
      - eap_identity: yes
      - eap_radius: yes
      - sql: no
      - sqlite: no
      - md4: yes # required by eap-mschapv2
      - mediation: yes
      - openssl: yes
      - blowfish: yes
      - twofish: yes
      - serpent: yes
      - kernel_pfkey: yes
      - integrity_test: yes
      - leak_detective: yes
      - load_tests: yes

